name: watch-with-dad-k8s
root: ~/workspace/watch-with-dad
startup_pane: 3
windows:
  - main:
      layout: even-vertical
      panes:
        - watch -n1 kubectl get services
        - watch -n1 kubectl get pods
        -
