apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-with-dad-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-with-dad-ui
  template:
    metadata:
      labels:
        app: watch-with-dad-ui
    spec:
      containers:
        - name: ui
          image: jgaebel/ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-ui
  labels:
    type: cloud
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: watch-with-dad-ui
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-ui-local-testing
  labels:
    type: local
spec:
  type: LoadBalancer
  ports:
    - name: ui-testing
      port: 3000
      targetPort: 80
      protocol: TCP
  selector:
    app: watch-with-dad-ui
