apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-with-dad-api
  namespace: watch-with-dad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-with-dad-api
  template:
    metadata:
      labels:
        app: watch-with-dad-api
    spec:
      containers:
        - name: api
          image: jgaebel/api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          readinessProbe:
            tcpSocket:
              port: 9090
          livenessProbe:
            tcpSocket:
              port: 9090
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-api
spec:
  ports:
    - name: api
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: watch-with-dad-api
