apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-with-dad-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-with-dad-ui
  template:
    metadata:
      labels:
        app: watch-with-dad-ui
    spec:
      containers:
        - name: ui
          image: joe/ui
          ports:
            - containerPort: 80
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-ui
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: ui
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: watch-with-dad-ui
