apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-with-dad-ui
  namespace: watch-with-dad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-with-dad-ui
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: watch-with-dad-ui
    spec:
      containers:
        - name: ui
          image: jgaebel/ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-ui
  namespace: watch-with-dad
  labels:
    type: cloud
spec:
  type: LoadBalancer
  loadBalancerIP: 35.244.101.219
  ports:
    - name: ui
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: watch-with-dad-ui
---
apiVersion: v1
kind: Service
metadata:
  name: watch-with-dad-ui-local-testing
  namespace: watch-with-dad
  labels:
    type: local
spec:
  type: LoadBalancer
  ports:
    - name: ui-testing
      port: 3000
      targetPort: 80
      protocol: TCP
  selector:
    app: watch-with-dad-ui
